---
- name: Ensure variables are set
  ansible.builtin.assert:
    that:
      - zsh_dependencies is defined
      - zsh_executable is defined
      - zsh_config_mode is defined
      - zsh_config_backup is defined
      - zsh_config_overwrite is defined
      - zsh_users_config is defined
      - zsh_system_config is defined
      - zsh_users is defined

- name: Ensure zsh with dependencies are installed
  ansible.builtin.apt:
    name: "{{ ['zsh'] + zsh_dependencies }}"
    state: present
    update_cache: true
  become: true
  tags:
    - zsh
    - dependencies

- name: Create zsh system files
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.filepath }}"
    mode: "{{ zsh_config_mode }}"
    backup: "{{ zsh_config_backup }}"
    force: "{{ zsh_config_overwrite }}"
  become: true
  loop: "{{ zsh_system_config }}"
  tags:
    - zsh
    - config

# Make sure that the default shell is zsh and the user settings are distributed.
- name: Distribute zsh user settings
  ansible.builtin.include_tasks: users.yml
  tags:
    - zsh
    - config
    - shell
  loop: "{{ zsh_users }}"
  loop_control:
    loop_var: zsh_user
